spin_manifest_version = "1"
authors = ["Gerrit Schrader <gerrit.schrader@sti.valantic.com>"]
description = "Serverless WebAssembly demo for Valantic STI monthly meeting"
name = "demo"
trigger = { type = "http", base = "/" }
version = "0.1.0"

[[component]]
id = "simple"
source = "simple.wasm"
environment = { URL = "https://raw.githubusercontent.com/fermyon/spin/main/Cargo.toml" }
[component.trigger]
route = "/simple"
[component.build]
command = "spin py2wasm simple -o simple.wasm"
watch = ["simple.py", "Pipfile"]

[[component]]
id = "outbound"
source = "outbound.wasm"
allowed_http_hosts = ["demo-xtzjs1xt.fermyon.app"]
[component.trigger]
route = "/outbound"
[component.build]
command = "spin py2wasm outbound -o outbound.wasm"
watch = ["outbound.py", "Pipfile"]
