spin_manifest_version = "1"
authors = ["Gerrit Schrader <gerrit.schrader@gmail.com>"]
description = "Serverless Webassembly showcase for Valantic STI monthly meeting"
name = "monthly-meeting-wasm-demo"
trigger = { type = "http", base = "/" }
version = "0.1.0"

[[component]]
id = "wasm-demo"        # component name
source = "app.wasm"     # WebAssembly module associated to component

[component.trigger]
route = "/..."          # component's wildcard route

[component.build]
command = "spin py2wasm app -o app.wasm"
watch = ["app.py", "Pipfile"]
